### PR TITLE
Modify little things

### PR DESCRIPTION
**Pull request by ElFamosoComore**
u must accept this pull request

### CODE REVIEW

**Comment by Nathanael2611** [comment]
Je ne vais pas accepter ce pull-request car il s'agit d'un petit troll de la part de notre cher ami de la forêt, Comore.

**Comment by ElFamosoComore** [comment]
i dont understand french

**Comment by Nathanael2611** [comment]
Ah... It's sad.

**Comment by ElFamosoComore** [comment]
so, can u translate

**Comment by Nathanael2611** [comment]
I'm not going to accept this sweater because it's a little troll from our dear friend from the forest, Comore.

**Comment by ElFamosoComore** [comment]
"sweater" stop using google translator idiot

**Comment by Nathanael2611** [comment]
"sweater" ? I don't know where you see this word! 😅

**Comment by ElFamosoComore** [comment]
idiot
image

**Comment by Nathanael2611** [comment]
👍

**Comment by ElFamosoComore** [comment]
so, accept my pull request

**Comment by Nathanael2611** [comment]
No.

**Comment by ElFamosoComore** [comment]
yes

**Comment by Nathanael2611** [comment]
No.

**Comment by ElFamosoComore** [comment]
yes

**Comment by Nathanael2611** [comment]
No.

**Pull request closed without merging**
